package com.recycleapp.backend.enums;

public enum WASTE_CATEGORIES {
    WASTE_BIOLOGICAL,
    WASTE_COLORED_GLASS,
    WASTE_ELECTRONICS,
    WASTE_METAL_FOOD_PACKAGING,
    WASTE_PAPER,
    WASTE_PLASTIC,
    WASTE_TEXTILE,
    WASTE_TOYS,
    WASTE_WHITE_GLASS
}
